{
    "language": "en",
    "text": "8.1 Installation and Setup",
    "key": "46\\27\\b4\\60\\d4\\49\\20\\b4",
    "ko": [
        {
            "text": "8.1 설치 및 설정",
            "timestamp": "2022-08-15 07:33:27",
            "email": "infohojin@gmail.com"
        },
        {
            "text": "8.1 Installation and Setup",
            "timestamp": "2022-08-15 07:33:17",
            "email": "infohojin@gmail.com"
        }
    ]
}